name = "Moonshine"
uuid = "99b31415-443e-43a2-8bf4-ca532bb4a161"
version = "0.3.9"
authors = ["Patrick Fournier <p_fournier@hushmail.com>"]

[deps]
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
CpuId = "adafc99b-e345-5852-983c-f28acb93d879"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LayeredLayouts = "f4a74d36-062a-4d48-97cd-1356bad1de4e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"

[weakdeps]
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"

[extensions]
MoonshineMakie = "GraphMakie"

[compat]
Bumper = "0.7.1"
ChunkSplitters = "3.1.2"
CondaPkg = "0.2.28"
CpuId = "0.3.1"
DataStructures = "0.19.3"
Distributions = "0.25"
DocStringExtensions = "0.9.4"
DoubleFloats = "1.4.3"
GeometryBasics = "0.5.7"
GraphMakie = "0.6.3"
Graphs = "1.8"
IntervalSets = "0.7.4"
JSON = "1.3.0"
LayeredLayouts = "0.2.10"
LinearAlgebra = "1.11"
NetworkLayout = "0.4.10"
Preferences = "1.5.0"
ProgressMeter = "1.10.4"
PythonCall = "0.9.24"
Random = "1.8"
RandomNumbers = "1.6.0"
SIMD = "3.7.1"
SpecialFunctions = "2.5.1"
StaticArrays = "1.9.13"
Statistics = "1.11.1"
StatsAPI = "1.7.0"
StatsBase = "0.34.4"
StatsFuns = "1.5.0"
UnicodePlots = "3.7.2"
UnsafeArrays = "1.0.7"
julia = "1.11"
